name: flutil
author: Gabriel Soares <soaresggm@gmail.com>
homepage: https://github.com/gosoares/flutil
description: Flutter utilities
version: 0.0.1

environment:
  sdk: ">=2.0.0-dev.35 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  rxdart: ^0.21.0
  connectivity: ^0.4.2+2